#ifndef PLUGIN_REGISTRATION_ERRORS_H
#define PLUGIN_REGISTRATION_ERRORS_H

typedef enum
{
    FAILED_TO_GET_PLUGIN_IDENTITY,

    FAILED_TO_SET_PLUGIN_DESCRIPTION,

    FAILED_TO_SET_PLUGIN_LDAP_PROTOCOL_VERSION,

    FAILED_TO_SET_PLUGIN_BIND_REQUEST_HANDLER,

    FAILED_TO_SET_PLUGIN_BIND_POLICY
}
plugin_registration_error_t;

#endif  // PLUGIN_REGISTRATION_ERRORS_H
