#ifndef GATEKEEPER_BIND_REQUEST_STATUS_T_H
#define GATEKEEPER_BIND_REQUEST_STATUS_T_H

typedef enum
{
    REQUEST_GRANTED = 0,

    REQUEST_DENIED = 1,

    REQUEST_DN_FETCH_FAILURE,

    REQUEST_IP_FETCH_FAILURE,

    REQUEST_DNS_FETCH_FAILURE,

    REQUEST_ROLES_FETCH_FAILURE,

    REQUEST_GROUPS_FETCH_FAILURE,

    REQUEST_ATTRIBUTES_FETCH_FAILURE,

    REQUEST_PARAMETERS_FETCH_SUCCESS,

    REQUEST_SATISFIED_GRANT_RULES,

    REQUEST_SATISFIED_DENY_RULES
}
bind_request_status_t, bind_request_error_t;

#endif  // GATEKEEPER_BIND_REQUEST_STATUS_T_H
