#ifndef BIND_REQUEST_RESOLVER_ERRORS_H
#define BIND_REQUEST_RESOLVER_ERRORS_H

typedef enum
{
    FAILED_TO_RESOLVE_CLIENT_DN,

    FAILED_TO_RESOLVE_CLIENT_IP,

    FAILED_TO_RESOLVE_CLIENT_DNS,

    FAILED_TO_RESOLVE_CLIENT_GROUPS,

    FAILED_TO_RESOLVE_CLIENT_ATTRIBUTES,

    FAILED_TO_FETCH_REQUEST_DATETIME
}
bind_request_resolver_error_t;

#endif  // BIND_REQUEST_RESOLVER_ERRORS_H
